# Asimov project config
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "kinship-protocol"
  type: docs

description: "Game-theoretic research proving cooperation dominance via kinship signaling"

stack:
  - "markdown"
  - "mermaid"
  - "game-theory"

conventions:
  - "ATX-style headers (#)"
  - "One sentence per line (for git diffs)"
  - "Mermaid for diagrams"
